version: "3.8"
services: 
    openldap:
        build: ./openldap
        ports:
            - "389:389"
            - "636:636"
        volumes: 
            - "./openldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif"
        command: 
            - "--copy-service"

    freeradius:
        build: ./freeradius
        ports:
            - "1812:1812/udp"
            - "1813:1813/udp"
        depends_on: 
            - openldap

        restart: "always"

    webapp:
        build: ./webapp
        ports:
            - "80:80"
        depends_on: 
            - freeradius

    hostapd:
        build: ./hostapd
        privileged: true
        network_mode: host
        environment: 
            - "INTERFACE=wlp2s0"
            - "SSID=wifi-lab-eap"
        depends_on: 
            - webapp