version: "3.8"
services: 
    webapp:
        build: ./webapp
        ports:
            - "80:80"
    openldap:
        build: ./openldap
        ports:
            - "389:389"
            - "636:636"
        volumes: 
            - "./openldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif"
        command: 
            - "--copy-service"

    freeradius:
        build: ./freeradius
        ports:
            - "1812:1812/udp"
            - "1813:1813/udp"
        environment:
            - "LDAP_HOST=openldap"
            - "LDAP_USER=cn=admin,dc=example,dc=org"
            - "LDAP_PASS=admin"
            - "LDAP_BASEDN=dc=example,dc=org"
            - "LDAP_USER_BASEDN=ou=Users,dc=example,dc=org"
            - "LDAP_GROUP_BASEDN=ou=Groups,dc=example,dc=com"
            - "RADIUS_CLIENT_CREDENTIALS=0.0.0.0:password1234"
            - "RADIUSD_ARGS=-X -f -l stdout"
        restart: "always"

    hostapd:
        build: ./hostapd
        privileged: true
        network_mode: host
        environment: 
            - "INTERFACE=wlp2s0"
            - "SSID=wifi-lab"
            - "WPA_PASSPHRASE=passw0rd"
